layout_spectrum: 0.3685899357725451
typography_spectrum: 0.6011503027894968
color:
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
  brandStrength: 0.8397074443082518
  lightness: 0.525013013463744
  saturation: 0.7642949447657286
  rhythmicContrast: 0.20175424176959858
coverPrefs:
  filter: false
github: true
name: Monsters
url: 'https://www.bedtimeforbigmonsters.com/'
navigation:
  - name: Business Models
    id: 40b4f80c-7a72-47f6-947b-ee7470699a2a
    type: content
favicon: null
title: I ♥ complexity
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/365095c7-99af-40b6-b9aa-11ef03b0058c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/365095c7-99af-40b6-b9aa-11ef03b0058c.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Weaving user centered design, agile engineering, and product development for
  planetary goodness. 
purpose:
  - type: external
    label: Schedule a short hello
    url: 'https://calendly.com/monsters'
