typography_spectrum: 0.2791909662990988
color:
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
  brandStrength: 0.14103365292652778
  lightness: 0.0995459921492983
  saturation: 0.49196839678377874
  rhythmicContrast: 0.6280131566437828
github: true
layout_spectrum: 0.7929579435295361
name: Monsters
url: 'https://www.bedtimeforbigmonsters.com/'
navigation:
  - name: Business Models
    id: 40b4f80c-7a72-47f6-947b-ee7470699a2a
    type: content
favicon: null
title: Bedtime for Big Monsters
content: []
coverPrefs:
  filter: false
description: >-
  I help teams weave user centered design, agile engineering, and product
  development together for planetary goodness. 
purpose:
  - type: external
    label: Schedule a short hello
    url: 'https://calendly.com/monsters'
