layout_spectrum: 0.1274607238546936
typography_spectrum: 0.6023613593743948
color:
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
  brandStrength: 0.07622269119099152
  lightness: 0.49867482000445523
  saturation: 0.013994097260039043
  rhythmicContrast: 0.24901803049249666
coverPrefs:
  filter: false
github: true
name: Monsters
url: 'https://www.bedtimeforbigmonsters.com/'
navigation:
  - name: Business Models
    id: 40b4f80c-7a72-47f6-947b-ee7470699a2a
    type: content
favicon: null
title: I ♥ complexity
content: []
description: >-
  Weaving user centered design, agile engineering, and product development for
  planetary goodness. 
purpose:
  - type: external
    label: Schedule a short hello
    url: 'https://calendly.com/monsters'
