typography_spectrum: 0.2871899328556023
color:
  brandStrength: 0.1104517174404262
  lightness: 0.3426448412595483
  saturation: 0.2767961877742137
  rhythmicContrast: 0.8927386678295155
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
github: true
layout_spectrum: 0.1273010527279855
name: Bedtime for Big Monsters
url: 'http://bedtimeforbigmonsters.com'
title: Bedtime for Big Monsters
content: []
description: Lullabies of social change
purpose:
  - type: contact
    url: 'mailto:eek@bedtimeforbigmonsters.com'
    label: Report a Monster
  - type: internal
    label: 'Rest your feet '
    item: 7e809649-de03-4770-8b43-a39fb6a6b103
