layout_spectrum: 0.1274607238546936
typography_spectrum: 0.6023613593743948
color:
  brandColors:
    - '#25064D'
    - '#36175E'
    - '#553285'
    - '#7B52AB'
    - '#9768D1'
  brandStrength: 0.07622269119099152
  lightness: 0.49867482000445523
  saturation: 0.013994097260039043
  rhythmicContrast: 0.24901803049249666
coverPrefs:
  filter: false
github: true
name: Monsters
url: 'https://www.bedtimeforbigmonsters.com/'
navigation:
  - name: Business Models
    id: 40b4f80c-7a72-47f6-947b-ee7470699a2a
    type: content
favicon: null
title: I ♥ complexity
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/365095c7-99af-40b6-b9aa-11ef03b0058c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/365095c7-99af-40b6-b9aa-11ef03b0058c.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      inLanguage: !<tag:yaml.org,2002:js/undefined> ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: >-
  Weaving user centered design, agile engineering, and product development for
  planetary goodness. 
purpose:
  - type: external
    label: Schedule a short hello
    url: 'https://calendly.com/monsters'
