layout_spectrum: 0.6843865357511816
typography_spectrum: 0.7177621673837783
color:
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
  brandStrength: 0.9514761632958445
  lightness: 0.1317879827058699
  saturation: 0.7644174556860166
  rhythmicContrast: 0.32269440297350876
coverPrefs:
  filter: false
github: true
name: Monsters
url: 'https://www.bedtimeforbigmonsters.com/'
navigation:
  - name: Business Models
    id: 40b4f80c-7a72-47f6-947b-ee7470699a2a
    type: content
favicon: null
title: I ♥ complexity
content: []
description: >-
  Weaving user centered design, agile engineering, and product development for
  planetary goodness. 
purpose:
  - type: external
    label: Schedule a short hello
    url: 'https://calendly.com/monsters'
