name: Bedtime for Big Monsters
layout_spectrum: 0.1273010527279855
typography_spectrum: 0.2871899328556023
color:
  brandColors:
    - '#7D8A2E'
    - '#C9D787'
    - '#FFFFFF'
    - '#FFC0A9'
    - '#FF8598'
  brandStrength: 0.1104517174404262
  lightness: 0.3426448412595483
  saturation: 0.2767961877742137
  rhythmicContrast: 0.8927386678295155
purpose:
  - type: contact
    label: Report a Monster
    url: 'mailto:eek@bedtimeforbigmonsters.com'
  - type: internal
    label: 'Repose your soul '
    item: 7e809649-de03-4770-8b43-a39fb6a6b103
title: Bedtime for Big Monsters
description: Lullabies of social change
navigation:
  - name: Sing you own Song
    id: 7e809649-de03-4770-8b43-a39fb6a6b103
    type: content
content: []
github: true
